# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d81d917989454c465f49f239f6e0f07a3992ee57478fbd716e411667526bcbab69ea31224f5e01fa6940758037829584b450bdc983c716786c34d227a7ced60

test:
  secret_key_base: 5e7c1a2674a44e3b51fd6bda5d632e592b40962442a054f271e4a39460564789203405e9f27afb6eca5a5cb947ababd81ef40ca6421c804d093a4d31170272ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
